
event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"
